// Dynamic Template Editor UI Schemas
// Automatically generated by scripts/generate_template_schemas.js based on dynamic Playwright analyses.
// Do NOT modify this file manually!

export type SchemaElement =
  | { type: 'text' | 'textarea' | 'list'; label: string; path: string[]; imageConfig?: never }
  | { type: 'image'; label: string; path?: never; imageConfig: { arrayKey: 'clinicImages' | 'treatmentImages' | 'otherImages'; index: number } };

export type SchemaSection = {
  label: string;
  elements: SchemaElement[];
};

export type SchemaPage = {
  id: string;
  label: string;
  sections: SchemaSection[];
};

export type TemplateSchema = {
  pages: SchemaPage[];
};

export const SHARED_PAGES: SchemaPage[] = [
  {
    "id": "home",
    "label": "Home Page",
    "sections": [
      {
        "label": "Hero Section",
        "elements": [
          {
            "type": "text",
            "label": "Studio Name",
            "path": [
              "clinic",
              "name"
            ]
          },
          {
            "type": "text",
            "label": "Hero Tagline",
            "path": [
              "clinic",
              "tagline"
            ]
          },
          {
            "type": "textarea",
            "label": "Studio Description",
            "path": [
              "clinic",
              "description"
            ]
          },
          {
            "type": "image",
            "label": "Hero Main Banner Image",
            "imageConfig": {
              "arrayKey": "clinicImages",
              "index": 0
            }
          },
          {
            "type": "list",
            "label": "Highlights List (1 per line)",
            "path": [
              "business",
              "highlights"
            ]
          }
        ]
      },
      {
        "label": "About Us Section",
        "elements": [
          {
            "type": "text",
            "label": "Principal Designer Name",
            "path": [
              "doctor",
              "name"
            ]
          },
          {
            "type": "text",
            "label": "Designer Experience Details",
            "path": [
              "doctor",
              "experience"
            ]
          },
          {
            "type": "image",
            "label": "Principal Portrait Image",
            "imageConfig": {
              "arrayKey": "otherImages",
              "index": 0
            }
          }
        ]
      },
      {
        "label": "Services Section",
        "elements": [
          {
            "type": "list",
            "label": "Services List (1 per line)",
            "path": [
              "business",
              "services"
            ]
          }
        ]
      },
      {
        "label": "Contact Section",
        "elements": [
          {
            "type": "text",
            "label": "Contact Phone Number",
            "path": [
              "clinic",
              "contact",
              "phone"
            ]
          },
          {
            "type": "text",
            "label": "Full Address location",
            "path": [
              "clinic",
              "address",
              "full"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "about",
    "label": "About Page",
    "sections": [
      {
        "label": "About Us Section",
        "elements": [
          {
            "type": "text",
            "label": "Studio Name",
            "path": [
              "clinic",
              "name"
            ]
          },
          {
            "type": "textarea",
            "label": "Studio Description",
            "path": [
              "clinic",
              "description"
            ]
          },
          {
            "type": "image",
            "label": "Clinic / Studio Gallery Image 2",
            "imageConfig": {
              "arrayKey": "clinicImages",
              "index": 1
            }
          }
        ]
      },
      {
        "label": "Creative Leadership - Lead",
        "elements": [
          {
            "type": "text",
            "label": "Principal Designer Name",
            "path": [
              "doctor",
              "name"
            ]
          },
          {
            "type": "image",
            "label": "Principal Portrait Image",
            "imageConfig": {
              "arrayKey": "otherImages",
              "index": 0
            }
          }
        ]
      }
    ]
  },
  {
    "id": "services",
    "label": "Services Page",
    "sections": [
      {
        "label": "Services Section",
        "elements": [
          {
            "type": "list",
            "label": "Services List (1 per line)",
            "path": [
              "business",
              "services"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "gallery",
    "label": "Gallery Page",
    "sections": [
      {
        "label": "Portfolio Gallery Section",
        "elements": [
          {
            "type": "list",
            "label": "Highlights List (1 per line)",
            "path": [
              "business",
              "highlights"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "contact",
    "label": "Contact Page",
    "sections": [
      {
        "label": "Contact Section",
        "elements": [
          {
            "type": "text",
            "label": "Contact Phone Number",
            "path": [
              "clinic",
              "contact",
              "phone"
            ]
          },
          {
            "type": "text",
            "label": "Full Address location",
            "path": [
              "clinic",
              "address",
              "full"
            ]
          }
        ]
      }
    ]
  }
];

export const TEMPLATE_SCHEMAS: Record<string, TemplateSchema> = {
  template1: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Designing Beyond The Surface.",
            elements: [
              {
                type: 'text',
                label: "Title",
                path: ['philosophy', 'title']
              },
              {
                type: 'text',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
          {
            label: "Journey Timeline",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Vision",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "Meet Our Design Leaders",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Transformations & Styling",
            elements: [
              {
                type: 'textarea',
                label: "Vision Quote",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "The Navaneeth Interiors Studio Differenc...",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Let's Shape Your Dream Space.",
            elements: [
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
    ]
  },
  template2: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'text',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
            ]
          },
          {
            label: "Why Choose Us",
            elements: [
              {
                type: 'textarea',
                label: "Country",
                path: ['clinic', 'address', 'country']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
          {
            label: "Journey Timeline",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "The Creative Designers",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
            ]
          },
          {
            label: "Turnkey Transparency & Execution Trust",
            elements: [
              {
                type: 'textarea',
                label: "Vision",
                path: ['about', 'vision']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
          {
            label: "Core Design & Fabrication Specialties",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "The Chennai Curation Library",
            elements: [
              {
                type: 'textarea',
                label: "Partner Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Vision",
                path: ['about', 'vision']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Let's Collaborate On Your Dream Space",
            elements: [
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
    ]
  },
  template3: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'text',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
            ]
          },
          {
            label: "Frequently Asked Questions",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Vision Quote",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Meet The Design Leaders",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'textarea',
                label: "Principal Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Partner Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'for-clients',
        label: "For Clients Page",
        sections: [
        ]
      },
    ]
  },
  template4: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
            ]
          },
          {
            label: "Precision In Every Detail",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Vision Quote",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "Journey Timeline",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Partner Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Partner Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template6: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
            ]
          },
          {
            label: "Frequently Asked Questions",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template7: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Crafting Timeless Spaces With Purpose An...",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
            ]
          },
          {
            label: "Ready To Take The Next Step?",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
            ]
          },
          {
            label: "Why Choose Us",
            elements: [
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Ready To Take The Next Step?",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Essential Styling",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Why Choose Us",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Ready For Yournew Space?",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'appointment',
        label: "Appointment Page",
        sections: [
        ]
      },
      {
        id: 'privacy',
        label: "Privacy Page",
        sections: [
        ]
      },
      {
        id: 'team',
        label: "Team Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
              {
                type: 'text',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Country",
                path: ['clinic', 'address', 'country']
              },
            ]
          },
        ]
      },
      {
        id: 'terms',
        label: "Terms Page",
        sections: [
          {
            label: "7. Governing Law",
            elements: [
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'textarea',
                label: "Country",
                path: ['clinic', 'address', 'country']
              },
            ]
          },
        ]
      },
    ]
  },
  template8: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Your Trusted Interior Design Partners",
            elements: [
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template10: {
    pages: [
      {
        id: "home",
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              { type: "text", label: "Studio Name", path: ["clinic", "name"] },
              { type: "text", label: "Hero Tagline", path: ["clinic", "tagline"] },
              { type: "textarea", label: "Studio Description", path: ["clinic", "description"] },
              { type: "image", label: "Hero Main Banner Image", imageConfig: { arrayKey: "clinicImages", index: 0 } },
            ]
          },
          {
            label: "Quality Assurances Section",
            elements: [
              { type: "list", label: "Highlights List (1 per line)", path: ["business", "highlights"] },
              { type: "image", label: "Quality Audit Image", imageConfig: { arrayKey: "clinicImages", index: 1 } },
            ]
          },
          {
            label: "Leadership & Credentials Section",
            elements: [
              { type: "text", label: "Principal Architect Name", path: ["doctor", "name"] },
              { type: "text", label: "Architect Experience Details", path: ["doctor", "experience"] },
              { type: "text", label: "Specialization Details", path: ["doctor", "specialization"] },
              { type: "image", label: "Principal Architect Portrait", imageConfig: { arrayKey: "otherImages", index: 0 } },
            ]
          },
          {
            label: "Featured Projects Section",
            elements: [
              { type: "image", label: "Project Showcase 1", imageConfig: { arrayKey: "otherImages", index: 1 } },
              { type: "image", label: "Project Showcase 2", imageConfig: { arrayKey: "otherImages", index: 2 } },
              { type: "image", label: "Project Showcase 3", imageConfig: { arrayKey: "otherImages", index: 3 } },
              { type: "image", label: "Project Showcase 4", imageConfig: { arrayKey: "otherImages", index: 4 } },
              { type: "image", label: "Project Showcase 5", imageConfig: { arrayKey: "otherImages", index: 5 } },
              { type: "image", label: "Project Showcase 6", imageConfig: { arrayKey: "otherImages", index: 6 } },
            ]
          },
          {
            label: "CTA Banner Section",
            elements: [
              { type: "text", label: "Contact Phone Number", path: ["clinic", "contact", "phone"] },
            ]
          }
        ]
      },
      {
        id: "about",
        label: "About Page",
        sections: [
          {
            label: "Hero Banner Section",
            elements: [
              { type: "text", label: "Studio Name", path: ["clinic", "name"] },
              { type: "text", label: "Hero Tagline", path: ["clinic", "tagline"] },
            ]
          },
          {
            label: "About Narrative Section",
            elements: [
              { type: "textarea", label: "Studio Description", path: ["clinic", "description"] },
              { type: "image", label: "Studio Engineering Image", imageConfig: { arrayKey: "clinicImages", index: 1 } },
            ]
          },
          {
            label: "Leadership & Credentials Section",
            elements: [
              { type: "text", label: "Principal Architect Name", path: ["doctor", "name"] },
              { type: "text", label: "Architect Experience Details", path: ["doctor", "experience"] },
              { type: "text", label: "Specialization Details", path: ["doctor", "specialization"] },
              { type: "image", label: "Principal Architect Portrait", imageConfig: { arrayKey: "otherImages", index: 0 } },
            ]
          },
          {
            label: "Highlights Section",
            elements: [
              { type: "list", label: "Highlights List (1 per line)", path: ["business", "highlights"] },
            ]
          }
        ]
      },
      {
        id: "services",
        label: "Services Page",
        sections: [
          {
            label: "Hero Banner Section",
            elements: [
              { type: "text", label: "Studio Name", path: ["clinic", "name"] },
              { type: "text", label: "Hero Tagline", path: ["clinic", "tagline"] },
            ]
          },
          {
            label: "Our Services Section",
            elements: [
              { type: "list", label: "Services List (1 per line)", path: ["business", "services"] },
            ]
          },
          {
            label: "Standards & Assurances Section",
            elements: [
              { type: "list", label: "Highlights List (1 per line)", path: ["business", "highlights"] },
              { type: "image", label: "Certified Specifications Image", imageConfig: { arrayKey: "clinicImages", index: 1 } },
            ]
          }
        ]
      },
      {
        id: "gallery",
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Banner Section",
            elements: [
              { type: "text", label: "Studio Name", path: ["clinic", "name"] },
              { type: "text", label: "Hero Tagline", path: ["clinic", "tagline"] },
            ]
          },
          {
            label: "Gallery Grid Section",
            elements: [
              { type: "image", label: "Gallery Item 1", imageConfig: { arrayKey: "otherImages", index: 0 } },
              { type: "image", label: "Gallery Item 2", imageConfig: { arrayKey: "otherImages", index: 1 } },
              { type: "image", label: "Gallery Item 3", imageConfig: { arrayKey: "otherImages", index: 2 } },
              { type: "image", label: "Gallery Item 4", imageConfig: { arrayKey: "otherImages", index: 3 } },
              { type: "image", label: "Gallery Item 5", imageConfig: { arrayKey: "otherImages", index: 4 } },
              { type: "image", label: "Gallery Item 6", imageConfig: { arrayKey: "otherImages", index: 5 } },
            ]
          }
        ]
      },
      {
        id: "contact",
        label: "Contact Page",
        sections: [
          {
            label: "Hero Banner Section",
            elements: [
              { type: "text", label: "Studio Name", path: ["clinic", "name"] },
              { type: "text", label: "Hero Tagline", path: ["clinic", "tagline"] },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              { type: "text", label: "Contact Phone Number", path: ["clinic", "contact", "phone"] },
              { type: "text", label: "Full Address location", path: ["clinic", "address", "full"] },
            ]
          }
        ]
      }
    ]
  },
  base: {
    pages: SHARED_PAGES
  }
};
