// Dynamic Template Editor UI Schemas
// Automatically generated by scripts/generate_template_schemas.js based on dynamic Playwright analyses.
// Do NOT modify this file manually!

export type SchemaElement =
  | { type: 'text' | 'textarea' | 'list'; label: string; path: string[]; imageConfig?: never }
  | { type: 'image'; label: string; path?: never; imageConfig: { arrayKey: 'clinicImages' | 'treatmentImages' | 'otherImages'; index: number } };

export type SchemaSection = {
  label: string;
  elements: SchemaElement[];
};

export type SchemaPage = {
  id: string;
  label: string;
  sections: SchemaSection[];
};

export type TemplateSchema = {
  pages: SchemaPage[];
};

export const SHARED_PAGES: SchemaPage[] = [
  {
    "id": "home",
    "label": "Home Page",
    "sections": [
      {
        "label": "Hero Section",
        "elements": [
          {
            "type": "text",
            "label": "Studio Name",
            "path": [
              "clinic",
              "name"
            ]
          },
          {
            "type": "text",
            "label": "Hero Tagline",
            "path": [
              "clinic",
              "tagline"
            ]
          },
          {
            "type": "textarea",
            "label": "Studio Description",
            "path": [
              "clinic",
              "description"
            ]
          },
          {
            "type": "image",
            "label": "Hero Main Banner Image",
            "imageConfig": {
              "arrayKey": "clinicImages",
              "index": 0
            }
          },
          {
            "type": "list",
            "label": "Highlights List (1 per line)",
            "path": [
              "business",
              "highlights"
            ]
          }
        ]
      },
      {
        "label": "About Us Section",
        "elements": [
          {
            "type": "text",
            "label": "Principal Designer Name",
            "path": [
              "doctor",
              "name"
            ]
          },
          {
            "type": "text",
            "label": "Designer Experience Details",
            "path": [
              "doctor",
              "experience"
            ]
          },
          {
            "type": "image",
            "label": "Principal Portrait Image",
            "imageConfig": {
              "arrayKey": "otherImages",
              "index": 0
            }
          }
        ]
      },
      {
        "label": "Services Section",
        "elements": [
          {
            "type": "list",
            "label": "Services List (1 per line)",
            "path": [
              "business",
              "services"
            ]
          }
        ]
      },
      {
        "label": "Contact Section",
        "elements": [
          {
            "type": "text",
            "label": "Contact Phone Number",
            "path": [
              "clinic",
              "contact",
              "phone"
            ]
          },
          {
            "type": "text",
            "label": "Full Address location",
            "path": [
              "clinic",
              "address",
              "full"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "about",
    "label": "About Page",
    "sections": [
      {
        "label": "About Us Section",
        "elements": [
          {
            "type": "text",
            "label": "Studio Name",
            "path": [
              "clinic",
              "name"
            ]
          },
          {
            "type": "textarea",
            "label": "Studio Description",
            "path": [
              "clinic",
              "description"
            ]
          },
          {
            "type": "image",
            "label": "Clinic / Studio Gallery Image 2",
            "imageConfig": {
              "arrayKey": "clinicImages",
              "index": 1
            }
          }
        ]
      },
      {
        "label": "Creative Leadership - Lead",
        "elements": [
          {
            "type": "text",
            "label": "Principal Designer Name",
            "path": [
              "doctor",
              "name"
            ]
          },
          {
            "type": "image",
            "label": "Principal Portrait Image",
            "imageConfig": {
              "arrayKey": "otherImages",
              "index": 0
            }
          }
        ]
      }
    ]
  },
  {
    "id": "services",
    "label": "Services Page",
    "sections": [
      {
        "label": "Services Section",
        "elements": [
          {
            "type": "list",
            "label": "Services List (1 per line)",
            "path": [
              "business",
              "services"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "gallery",
    "label": "Gallery Page",
    "sections": [
      {
        "label": "Portfolio Gallery Section",
        "elements": [
          {
            "type": "list",
            "label": "Highlights List (1 per line)",
            "path": [
              "business",
              "highlights"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "contact",
    "label": "Contact Page",
    "sections": [
      {
        "label": "Contact Section",
        "elements": [
          {
            "type": "text",
            "label": "Contact Phone Number",
            "path": [
              "clinic",
              "contact",
              "phone"
            ]
          },
          {
            "type": "text",
            "label": "Full Address location",
            "path": [
              "clinic",
              "address",
              "full"
            ]
          }
        ]
      }
    ]
  }
];

export const TEMPLATE_SCHEMAS: Record<string, TemplateSchema> = {
  template1: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template2: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template3: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'for-clients',
        label: "For Clients Page",
        sections: [
        ]
      },
    ]
  },
  template4: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template6: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template7: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'appointment',
        label: "Appointment Page",
        sections: [
        ]
      },
      {
        id: 'privacy',
        label: "Privacy Page",
        sections: [
        ]
      },
      {
        id: 'team',
        label: "Team Page",
        sections: [
        ]
      },
      {
        id: 'terms',
        label: "Terms Page",
        sections: [
        ]
      },
    ]
  },
  template10: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Hero Main Banner Image",
                imageConfig: { arrayKey: 'clinicImages', index: 0 }
              },
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Designer Experience Details",
                path: ['doctor', 'experience']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'image',
                label: "Clinic / Studio Gallery Image 2",
                imageConfig: { arrayKey: 'clinicImages', index: 1 }
              },
            ]
          },
          {
            label: "Creative Leadership - Lead",
            elements: [
              {
                type: 'text',
                label: "Principal Designer Name",
                path: ['doctor', 'name']
              },
              {
                type: 'image',
                label: "Principal Portrait Image",
                imageConfig: { arrayKey: 'otherImages', index: 0 }
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  base: {
    pages: SHARED_PAGES
  }
};
