// Dynamic Template Editor UI Schemas
// Automatically generated by scripts/generate_template_schemas.js based on dynamic Playwright analyses.
// Do NOT modify this file manually!

export type SchemaElement =
  | { type: 'text' | 'textarea' | 'list'; label: string; path: string[]; imageConfig?: never }
  | { type: 'image'; label: string; path?: never; imageConfig: { arrayKey: 'clinicImages' | 'treatmentImages' | 'otherImages'; index: number } };

export type SchemaSection = {
  label: string;
  elements: SchemaElement[];
};

export type SchemaPage = {
  id: string;
  label: string;
  sections: SchemaSection[];
};

export type TemplateSchema = {
  pages: SchemaPage[];
};

export const SHARED_PAGES: SchemaPage[] = [
  {
    "id": "home",
    "label": "Home Page",
    "sections": [
      {
        "label": "Hero Section",
        "elements": [
          {
            "type": "text",
            "label": "Studio Name",
            "path": [
              "clinic",
              "name"
            ]
          },
          {
            "type": "text",
            "label": "Hero Tagline",
            "path": [
              "clinic",
              "tagline"
            ]
          },
          {
            "type": "textarea",
            "label": "Studio Description",
            "path": [
              "clinic",
              "description"
            ]
          },
          {
            "type": "image",
            "label": "Hero Main Banner Image",
            "imageConfig": {
              "arrayKey": "clinicImages",
              "index": 0
            }
          },
          {
            "type": "list",
            "label": "Highlights List (1 per line)",
            "path": [
              "business",
              "highlights"
            ]
          }
        ]
      },
      {
        "label": "About Us Section",
        "elements": [
          {
            "type": "text",
            "label": "Principal Designer Name",
            "path": [
              "doctor",
              "name"
            ]
          },
          {
            "type": "text",
            "label": "Designer Experience Details",
            "path": [
              "doctor",
              "experience"
            ]
          },
          {
            "type": "image",
            "label": "Principal Portrait Image",
            "imageConfig": {
              "arrayKey": "otherImages",
              "index": 0
            }
          }
        ]
      },
      {
        "label": "Services Section",
        "elements": [
          {
            "type": "list",
            "label": "Services List (1 per line)",
            "path": [
              "business",
              "services"
            ]
          }
        ]
      },
      {
        "label": "Contact Section",
        "elements": [
          {
            "type": "text",
            "label": "Contact Phone Number",
            "path": [
              "clinic",
              "contact",
              "phone"
            ]
          },
          {
            "type": "text",
            "label": "Full Address location",
            "path": [
              "clinic",
              "address",
              "full"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "about",
    "label": "About Page",
    "sections": [
      {
        "label": "About Us Section",
        "elements": [
          {
            "type": "text",
            "label": "Studio Name",
            "path": [
              "clinic",
              "name"
            ]
          },
          {
            "type": "textarea",
            "label": "Studio Description",
            "path": [
              "clinic",
              "description"
            ]
          },
          {
            "type": "image",
            "label": "Clinic / Studio Gallery Image 2",
            "imageConfig": {
              "arrayKey": "clinicImages",
              "index": 1
            }
          }
        ]
      },
      {
        "label": "Creative Leadership - Lead",
        "elements": [
          {
            "type": "text",
            "label": "Principal Designer Name",
            "path": [
              "doctor",
              "name"
            ]
          },
          {
            "type": "image",
            "label": "Principal Portrait Image",
            "imageConfig": {
              "arrayKey": "otherImages",
              "index": 0
            }
          }
        ]
      }
    ]
  },
  {
    "id": "services",
    "label": "Services Page",
    "sections": [
      {
        "label": "Services Section",
        "elements": [
          {
            "type": "list",
            "label": "Services List (1 per line)",
            "path": [
              "business",
              "services"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "gallery",
    "label": "Gallery Page",
    "sections": [
      {
        "label": "Portfolio Gallery Section",
        "elements": [
          {
            "type": "list",
            "label": "Highlights List (1 per line)",
            "path": [
              "business",
              "highlights"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "contact",
    "label": "Contact Page",
    "sections": [
      {
        "label": "Contact Section",
        "elements": [
          {
            "type": "text",
            "label": "Contact Phone Number",
            "path": [
              "clinic",
              "contact",
              "phone"
            ]
          },
          {
            "type": "text",
            "label": "Full Address location",
            "path": [
              "clinic",
              "address",
              "full"
            ]
          }
        ]
      }
    ]
  }
];

export const TEMPLATE_SCHEMAS: Record<string, TemplateSchema> = {
  template1: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Designing Beyond The Surface.",
            elements: [
              {
                type: 'text',
                label: "Title",
                path: ['philosophy', 'title']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
          {
            label: "Journey Timeline",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Vision",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "Meet Our Design Leaders",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "The Navaneeth Interiors Studio Differenc...",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Let's Shape Your Dream Space.",
            elements: [
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
    ]
  },
  template2: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'text',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
            ]
          },
          {
            label: "Why Choose Us",
            elements: [
              {
                type: 'textarea',
                label: "Country",
                path: ['clinic', 'address', 'country']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
          {
            label: "Journey Timeline",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "The Creative Designers",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'text',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
          {
            label: "Core Design & Fabrication Specialties",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Let's Collaborate On Your Dream Space",
            elements: [
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
    ]
  },
  template3: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'text',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
            ]
          },
          {
            label: "Frequently Asked Questions",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Vision Quote",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Meet The Design Leaders",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Principal Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Partner Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
      {
        id: 'for-clients',
        label: "For Clients Page",
        sections: [
        ]
      },
    ]
  },
  template4: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
            ]
          },
          {
            label: "Precision In Every Detail",
            elements: [
              {
                type: 'list',
                label: "Highlights List (1 per line)",
                path: ['business', 'highlights']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Vision Quote",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "Journey Timeline",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Partner Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Partner Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template6: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
            ]
          },
          {
            label: "Frequently Asked Questions",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Mission Statement",
            elements: [
              {
                type: 'textarea',
                label: "Vision Quote",
                path: ['about', 'vision']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Meet The Design Leaders",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Partner Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  template10: {
    pages: [
      {
        id: 'home',
        label: "Home Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "Services Section",
            elements: [
              {
                type: 'list',
                label: "Services List (1 per line)",
                path: ['business', 'services']
              },
            ]
          },
          {
            label: "About Us Section",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'text',
                label: "Experience",
                path: ['doctor', 'experience']
              },
            ]
          },
          {
            label: "LAUNCH Loft PLAN",
            elements: [
              {
                type: 'textarea',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'textarea',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
              {
                type: 'textarea',
                label: "City",
                path: ['clinic', 'address', 'city']
              },
              {
                type: 'textarea',
                label: "State",
                path: ['clinic', 'address', 'state']
              },
            ]
          },
        ]
      },
      {
        id: 'about',
        label: "About Page",
        sections: [
          {
            label: "Portfolio Gallery Section",
            elements: [
              {
                type: 'textarea',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
            ]
          },
          {
            label: "The Design Directors",
            elements: [
              {
                type: 'text',
                label: "Name",
                path: ['doctor', 'name']
              },
              {
                type: 'textarea',
                label: "Principal Credentials",
                path: ['doctor', 'credentials']
              },
              {
                type: 'textarea',
                label: "Principal Bio",
                path: ['doctor', 'bio']
              },
              {
                type: 'textarea',
                label: "Principal Specialization",
                path: ['doctor', 'specialization']
              },
              {
                type: 'textarea',
                label: "Quote",
                path: ['doctor', 'quote']
              },
              {
                type: 'textarea',
                label: "Partner Role",
                path: ['doctor2', 'role']
              },
              {
                type: 'text',
                label: "Name",
                path: ['doctor2', 'name']
              },
              {
                type: 'textarea',
                label: "Credentials",
                path: ['doctor2', 'credentials']
              },
              {
                type: 'textarea',
                label: "Bio",
                path: ['doctor2', 'bio']
              },
              {
                type: 'textarea',
                label: "Partner Quote",
                path: ['doctor2', 'quote']
              },
            ]
          },
        ]
      },
      {
        id: 'services',
        label: "Services Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'text',
                label: "Hero Tagline",
                path: ['clinic', 'tagline']
              },
            ]
          },
        ]
      },
      {
        id: 'gallery',
        label: "Gallery Page",
        sections: [
          {
            label: "Hero Section",
            elements: [
              {
                type: 'text',
                label: "Studio Name",
                path: ['clinic', 'name']
              },
              {
                type: 'textarea',
                label: "Studio Description",
                path: ['clinic', 'description']
              },
            ]
          },
        ]
      },
      {
        id: 'contact',
        label: "Contact Page",
        sections: [
          {
            label: "Contact Section",
            elements: [
              {
                type: 'text',
                label: "Contact Phone Number",
                path: ['clinic', 'contact', 'phone']
              },
              {
                type: 'text',
                label: "Full Address location",
                path: ['clinic', 'address', 'full']
              },
            ]
          },
        ]
      },
    ]
  },
  base: {
    pages: SHARED_PAGES
  }
};
